namespace Bb.Oracle.Models.Configurations
{
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// generated by Configuration Designer
    /// for more information on the tool, see http://devtm.fr
    /// </remarks>
    public partial class UserElement 
    {

        public UserElement()
        {

        }

        /// <summary>
        /// Name
        /// </summary>
        public System.String Name { get; set; }

        /// <summary>
        /// Email
        /// </summary>
        public System.String Email { get; set; }

        /// <summary>
        /// Is Techlead
        /// </summary>
        public System.Boolean IsTechlead { get; set; }

    }



}



